# Generated by Django 5.0 on 2023-12-08 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='sourse',
            new_name='source',
        ),
    ]
