# Generated by Django 5.0 on 2023-12-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0002_rename_sourse_route_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="distance",
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
